server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  cloud:
    gateway:
      routes:
        - id: movie-store
          uri: lb://movie-store
          predicates:
            - Path=/movie/**
        - id: time-sheet
          uri: lb://time-sheet
          predicates:
            - Path=/time/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

