
spring:
  datasource:
    url: jdbc:mysql://team-proj-2-mysql.czznqc9erwsv.us-east-2.rds.amazonaws.com:3306/db?serverTimezone=UTC
    username: dev
    password: dev123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"

